/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import persistence.PassageiroDAO;
import domain.Passageiro;
import domain.Categoria;
import javax.swing.JOptionPane;

/**
 *
 * @author notrealgabu
 */
public class CadastroDePassageiro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDePessoa
     */
    public CadastroDePassageiro() {
        initComponents();
        buttonGroupCategoria.add(rbPreferencial);
        buttonGroupCategoria.add(rbComum);
        buttonGroupCategoria.add(rbVip);
        this.setLocationRelativeTo(null);
        btCancelar.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCategoria = new javax.swing.ButtonGroup();
        panelNorth = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        panelSouth = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txId = new javax.swing.JTextField();
        txNome = new javax.swing.JTextField();
        txCPF = new javax.swing.JTextField();
        rbVip = new javax.swing.JRadioButton();
        rbPreferencial = new javax.swing.JRadioButton();
        rbComum = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        panelNorth.setBackground(new java.awt.Color(204, 0, 51));
        panelNorth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 20));

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        panelNorth.add(btNovo);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        panelNorth.add(btCancelar);

        getContentPane().add(panelNorth, java.awt.BorderLayout.PAGE_START);

        panelSouth.setBackground(new java.awt.Color(0, 0, 0));
        panelSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 200, 20));

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        panelSouth.add(btSalvar);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        panelSouth.add(btBuscar);

        getContentPane().add(panelSouth, java.awt.BorderLayout.PAGE_END);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Id");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel5.setText("Categoria");

        txId.setBackground(new java.awt.Color(204, 204, 204));
        txId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIdActionPerformed(evt);
            }
        });

        txNome.setBackground(new java.awt.Color(204, 204, 204));
        txNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNomeActionPerformed(evt);
            }
        });

        txCPF.setBackground(new java.awt.Color(204, 204, 204));
        txCPF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCPFActionPerformed(evt);
            }
        });

        rbVip.setText("VIP");

        rbPreferencial.setText("Preferencial");
        rbPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPreferencialActionPerformed(evt);
            }
        });

        rbComum.setText("Comum");

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbComum)
                    .addComponent(rbPreferencial)
                    .addComponent(rbVip))
                .addGap(232, 232, 232))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCenterLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(rbVip)
                .addGap(18, 18, 18)
                .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbPreferencial))
                .addGap(18, 18, 18)
                .addComponent(rbComum)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIdActionPerformed

    private void txNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNomeActionPerformed

    private void txCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCPFActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        passageiro = createPassageiro();
        cleanForm();
        new PassageiroDAO().save(passageiro);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        cleanForm();
        desabilitarCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        this.showPassageiro(passageiro);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void rbPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPreferencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPreferencialActionPerformed

    private void desabilitarCampos(){
        txId.setEnabled(false);
        txNome.setEnabled(false);
        txCPF.setEnabled(false);
        rbVip.setEnabled(false);
        rbComum.setEnabled(false);
        rbPreferencial.setEnabled(false);
    }
    
    private void habilitarCampos(){
        txId.setEnabled(true);
        txNome.setEnabled(true);
        txCPF.setEnabled(true);
        rbVip.setEnabled(true);
        rbComum.setEnabled(true);
        rbPreferencial.setEnabled(true);
    }
    
    private void cleanForm(){
        txId.setText("");
        txNome.setText("");
        txCPF.setText("");
        buttonGroupCategoria.clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CadastroDePassageiro().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroupCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JRadioButton rbComum;
    private javax.swing.JRadioButton rbPreferencial;
    private javax.swing.JRadioButton rbVip;
    private javax.swing.JTextField txCPF;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txNome;
    // End of variables declaration//GEN-END:variables

    private Passageiro passageiro;
    
    
    private void showPassageiro(Passageiro p){
        
        txId.setText(String.valueOf(p.getId()));
        txCPF.setText(p.getCpf());
        txNome.setText(p.getNome());
        
        if (p.getCategoria()== Categoria.COMUM)
            rbComum.setSelected(true);
        else if (p.getCategoria()== Categoria.VIP)
            rbVip.setSelected(true);
        else if (p.getCategoria()== Categoria.PREFERENCIAL)
            rbPreferencial.setSelected(true);
       
        
    }
    
    private Passageiro createPassageiro(){
        
        String nome = txNome.getText();
        String cpf = txCPF.getText();
        Categoria categoria;
        
        if (rbComum.isSelected())
           categoria = Categoria.COMUM;
        else if (rbVip.isSelected())
           categoria = Categoria.VIP;
        else
           categoria = Categoria.PREFERENCIAL;
        
        return new Passageiro (nome, cpf, categoria);
        
    }

    public Passageiro getPassageiro(){
        return this.passageiro;
    }
    
    public void setPessoa(Passageiro p){
        this.passageiro = p;
    }
    
}
